version: "3"

services:
  nats:
    image: nats
    command: "-c /etc/nats/nats.conf"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
